version: '3.8'

services:
  backend:
    build:
      context: ./backoffice
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/excellent_dev_teste
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "4200:5000"  # Alterado para 5000 (porta do serve)
  #   depends_on:
  #     - backend

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: excellent_dev_teste
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: